// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * PowerPoint Export Service
 *
 * Generates a single widescreen (16:9) .pptx slide from the current diagram
 * canvas image.  The slide theme (dark / light) matches the app's current
 * colour mode so the exported slide looks exactly like what the user sees.
 *
 * Library: PptxGenJS v4 (client-side, no backend required)
 */

import PptxGenJS from 'pptxgenjs';
import { generateModelFilename } from '../utils/modelNaming';

// ─── Theme palettes ───────────────────────────────────────────────────────────

interface SlideTheme {
  bg: string;
  headerBg: string;
  accent: string;
  titleText: string;
  metaText: string;
  footerText: string;
}

const DARK_THEME: SlideTheme = {
  bg: '1e293b',       // slate-800
  headerBg: '0f172a', // slate-900
  accent: '0078d4',   // Azure blue
  titleText: 'ffffff',
  metaText: '94a3b8', // slate-400
  footerText: '475569', // slate-600
};

const LIGHT_THEME: SlideTheme = {
  bg: 'f8fafc',       // slate-50
  headerBg: 'e2e8f0', // slate-200
  accent: '0078d4',   // Azure blue
  titleText: '0f172a', // slate-900
  metaText: '475569',  // slate-600
  footerText: '94a3b8', // slate-400
};

// ─── Slide layout constants (inches, LAYOUT_WIDE = 13.33" × 7.5") ────────────

const W = 13.33;  // slide width
const ACCENT_H = 0.07;
const HEADER_H = 0.83;
const HEADER_END = ACCENT_H + HEADER_H;   // 0.9"
const SEP_H = 0.04;
const IMAGE_Y = HEADER_END + SEP_H + 0.06; // ~1.0"
const IMAGE_X = 0.2;
const IMAGE_W = W - IMAGE_X * 2;           // 12.93"
const FOOTER_H = 0.28;
const FOOTER_Y = 7.5 - FOOTER_H - 0.08;   // ~7.14"
const IMAGE_H = FOOTER_Y - IMAGE_Y - 0.1; // remaining body height

// ─── Public export function ───────────────────────────────────────────────────

export interface PptxExportOptions {
  diagramName: string;
  author: string;
  date: string;
  isDarkMode: boolean;
}

/**
 * Build and download a single-slide PPTX containing the diagram image.
 * Returns the generated filename.
 */
export async function exportDiagramAsPptx(
  imageDataUrl: string,
  options: PptxExportOptions,
): Promise<string> {
  const { diagramName, author, date, isDarkMode } = options;
  const t = isDarkMode ? DARK_THEME : LIGHT_THEME;

  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';
  pptx.author = author;
  pptx.title = diagramName;
  pptx.subject = 'Azure Architecture Diagram';
  pptx.company = 'Microsoft Azure';

  const slide = pptx.addSlide();

  // ── Background ──────────────────────────────────────────────────────────────
  slide.background = { color: t.bg };

  // ── Top accent bar (Azure blue) ─────────────────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: 0, w: W, h: ACCENT_H,
    fill: { color: t.accent },
    line: { color: t.accent, width: 0 },
  });

  // ── Header strip ────────────────────────────────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: ACCENT_H, w: W, h: HEADER_H,
    fill: { color: t.headerBg },
    line: { color: t.headerBg, width: 0 },
  });

  // ── Diagram title ────────────────────────────────────────────────────────────
  slide.addText(diagramName, {
    x: 0.35, y: ACCENT_H + 0.05, w: 9.5, h: HEADER_H - 0.1,
    fontSize: 24,
    bold: true,
    color: t.titleText,
    fontFace: 'Yu Gothic UI',
    valign: 'middle',
    wrap: true,
  });

  // ── Author + date (right side of header) ────────────────────────────────────
  slide.addText(`${author}  ·  ${date}`, {
    x: 9.9, y: ACCENT_H + 0.05, w: 3.08, h: HEADER_H - 0.1,
    fontSize: 10,
    color: t.metaText,
    fontFace: 'Yu Gothic UI',
    align: 'right',
    valign: 'middle',
  });

  // ── Thin separator between header and image ──────────────────────────────────
  slide.addShape(pptx.ShapeType.rect, {
    x: 0, y: HEADER_END, w: W, h: SEP_H,
    fill: { color: t.accent },
    line: { color: t.accent, width: 0 },
  });

  // ── Diagram image ────────────────────────────────────────────────────────────
  slide.addImage({
    data: imageDataUrl,
    x: IMAGE_X,
    y: IMAGE_Y,
    w: IMAGE_W,
    h: IMAGE_H,
    sizing: { type: 'contain', w: IMAGE_W, h: IMAGE_H },
  });

  // ── Footer text ──────────────────────────────────────────────────────────────
  slide.addText('Generated by Azure Architecture Diagram Builder  ·  microsoft.com/azure', {
    x: 0.35, y: FOOTER_Y, w: W - 0.7, h: FOOTER_H,
    fontSize: 8,
    color: t.footerText,
    fontFace: 'Yu Gothic UI',
    valign: 'middle',
  });

  const fileName = generateModelFilename('azure-diagram-slide', 'pptx');
  await pptx.writeFile({ fileName });
  return fileName;
}
