// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Workflow Narrative Exporter
 * ---------------------------
 * Builds a Markdown document describing the current architecture and its
 * workflow narrative (the step-by-step data/process flow shown in the Workflow
 * panel), so users can save/share the design as prose alongside the diagram.
 *
 * Pure and additive: takes a snapshot of the diagram state and returns a
 * Markdown string. The caller triggers the download (mirrors exportAsSvg).
 */

import type { Node, Edge } from 'reactflow';

export interface WorkflowNarrativeInput {
  title: {
    architectureName: string;
    author: string;
    version: string;
    date: string;
  };
  prompt?: string;
  model?: { name: string; timeMs?: number } | null;
  nodes: Node[];
  edges: Edge[];
  workflow: Array<{ step: number; description: string; services: string[] }>;
  /** Optional WAF score (0-100) if the diagram has been validated. */
  validationScore?: number | null;
  /** Optional total monthly cost estimate. */
  totalMonthlyCost?: number;
  pricingMode?: string;
  region?: string;
}

/** Escape a value for safe use inside a Markdown table cell. */
function cell(value: string): string {
  return (value || '').replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

/**
 * Build a Markdown narrative for the given architecture snapshot.
 */
export function buildWorkflowMarkdown(input: WorkflowNarrativeInput): string {
  const {
    title,
    prompt,
    model,
    nodes,
    edges,
    workflow,
    validationScore,
    totalMonthlyCost,
    pricingMode,
    region,
  } = input;

  const serviceNodes = nodes.filter((n) => n.type === 'azureNode');
  const groupNodes = nodes.filter((n) => n.type === 'groupNode');

  // id -> display label (service type) for resolving workflow/connection refs.
  const labelById = new Map<string, string>();
  for (const n of nodes) {
    const label = (n.data as any)?.label;
    if (label) labelById.set(n.id, String(label));
  }

  // Resolve a workflow service ref (node id OR label) to a readable name.
  const resolveRef = (ref: string): string => labelById.get(ref) ?? ref;

  const lines: string[] = [];

  // ── Header ────────────────────────────────────────────────────────────
  lines.push(`# ${title.architectureName || 'Untitled Architecture'}`);
  lines.push('');
  const meta = [`**Author:** ${title.author || 'Azure Architect'}`, `**Version:** ${title.version || '1.0'}`, `**Date:** ${title.date || new Date().toLocaleDateString()}`];
  if (model?.name) {
    meta.push(`**Model:** ${model.name}${model.timeMs ? ` (${(model.timeMs / 1000).toFixed(1)}s)` : ''}`);
  }
  lines.push(meta.join(' · '));
  lines.push('');
  lines.push('> Generated by the Azure Architecture Diagram Builder.');
  lines.push('');

  // ── Overview / prompt ───────────────────────────────────────────────────
  if (prompt && prompt.trim()) {
    lines.push('## Overview');
    lines.push('');
    lines.push(prompt.trim());
    lines.push('');
  }

  // ── Services (grouped when the diagram uses groups) ──────────────────────
  lines.push(`## Services (${serviceNodes.length})`);
  lines.push('');
  if (serviceNodes.length === 0) {
    lines.push('_No services on the canvas yet._');
    lines.push('');
  } else if (groupNodes.length > 0) {
    for (const group of groupNodes) {
      const groupLabel = (group.data as any)?.label || 'Group';
      const members = serviceNodes.filter((n) => n.parentNode === group.id);
      if (members.length === 0) continue;
      lines.push(`### ${groupLabel}`);
      lines.push('');
      for (const n of members) {
        const desc = (n.data as any)?.description;
        lines.push(`- **${(n.data as any)?.label ?? 'Service'}**${desc ? ` — ${cell(String(desc))}` : ''}`);
      }
      lines.push('');
    }
    const ungrouped = serviceNodes.filter((n) => !n.parentNode || !groupNodes.some((g) => g.id === n.parentNode));
    if (ungrouped.length > 0) {
      lines.push('### Ungrouped');
      lines.push('');
      for (const n of ungrouped) {
        const desc = (n.data as any)?.description;
        lines.push(`- **${(n.data as any)?.label ?? 'Service'}**${desc ? ` — ${cell(String(desc))}` : ''}`);
      }
      lines.push('');
    }
  } else {
    for (const n of serviceNodes) {
      const desc = (n.data as any)?.description;
      lines.push(`- **${(n.data as any)?.label ?? 'Service'}**${desc ? ` — ${cell(String(desc))}` : ''}`);
    }
    lines.push('');
  }

  // ── Workflow narrative ───────────────────────────────────────────────────
  lines.push('## Workflow');
  lines.push('');
  if (!workflow || workflow.length === 0) {
    lines.push('_No workflow steps defined for this diagram._');
    lines.push('');
  } else {
    const ordered = [...workflow].sort((a, b) => (a.step ?? 0) - (b.step ?? 0));
    for (const s of ordered) {
      lines.push(`${s.step}. ${s.description}`);
      if (Array.isArray(s.services) && s.services.length > 0) {
        const names = s.services.map(resolveRef);
        lines.push(`   - _Services:_ ${names.join(' → ')}`);
      }
    }
    lines.push('');
  }

  // ── Connections ──────────────────────────────────────────────────────────
  if (edges.length > 0) {
    lines.push(`## Connections (${edges.length})`);
    lines.push('');
    lines.push('| From | To | Label |');
    lines.push('| --- | --- | --- |');
    for (const e of edges) {
      const from = labelById.get(e.source) ?? e.source;
      const to = labelById.get(e.target) ?? e.target;
      const label = typeof e.label === 'string' ? e.label : '';
      lines.push(`| ${cell(from)} | ${cell(to)} | ${cell(label)} |`);
    }
    lines.push('');
  }

  // ── Optional: validation + cost summary ──────────────────────────────────
  if (typeof validationScore === 'number') {
    lines.push('## Well-Architected Validation');
    lines.push('');
    lines.push(`**Score:** ${validationScore}/100`);
    lines.push('');
  }
  if (typeof totalMonthlyCost === 'number' && totalMonthlyCost > 0) {
    lines.push('## Estimated Monthly Cost');
    lines.push('');
    const term = pricingMode === 'reserved1yr' ? '1-year reserved' : 'pay-as-you-go';
    const where = region ? `, ${region}` : '';
    lines.push(`Approximately **$${totalMonthlyCost.toLocaleString(undefined, { maximumFractionDigits: 0 })}/mo** (${term}${where}).`);
    lines.push('');
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push('---');
  lines.push(`_Exported ${new Date().toISOString()}._`);
  lines.push('');

  return lines.join('\n');
}
