// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Interactive HTML Renderer for SpecKit Diagrams
 *
 * Generates a self-contained HTML file with an interactive architecture
 * diagram. Features pan, zoom, hover tooltips, and click-to-highlight.
 * No external dependencies — works offline by opening the file in any browser.
 *
 * Designed to be included in az prototype SpecKit bundles alongside the
 * markdown documentation, replacing Mermaid with professional visuals.
 */

import type { LayoutResult } from './layoutEngine.js';

// ── Public API ─────────────────────────────────────────────────────────

export function renderHtml(layout: LayoutResult, title?: string): string {
  const diagramTitle = title ?? 'Azure Architecture Diagram';

  // Serialize layout data for the client-side JS
  const layoutJson = JSON.stringify(layout);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(diagramTitle)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; background: #f8f9fa; overflow: hidden; }

  /* Header */
  .header {
    background: linear-gradient(135deg, #0078D4, #005A9E);
    color: white; padding: 12px 24px; display: flex; align-items: center; gap: 16px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15); z-index: 100; position: relative;
  }
  .header h1 { font-size: 18px; font-weight: 600; }
  .header .meta { font-size: 12px; opacity: 0.8; margin-left: auto; }
  .header .controls { display: flex; gap: 6px; }
  .header button {
    background: rgba(255,255,255,0.2); border: 1px solid rgba(255,255,255,0.3);
    color: white; padding: 4px 12px; border-radius: 4px; cursor: pointer; font-size: 12px;
  }
  .header button:hover { background: rgba(255,255,255,0.3); }

  /* Canvas */
  .canvas-container { width: 100vw; height: calc(100vh - 52px); overflow: hidden; position: relative; cursor: grab; }
  .canvas-container.dragging { cursor: grabbing; }
  .canvas { position: absolute; transform-origin: 0 0; }

  /* Nodes */
  .node {
    position: absolute; width: 200px; height: 70px; background: white;
    border-radius: 8px; border: 2px solid #ccc; box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    cursor: pointer; transition: box-shadow 0.2s, transform 0.2s;
    display: flex; flex-direction: column; justify-content: center; padding: 0 14px 0 20px;
    overflow: hidden;
  }
  .node:hover { box-shadow: 0 4px 16px rgba(0,0,0,0.15); transform: translateY(-1px); z-index: 10; }
  .node.highlighted { box-shadow: 0 0 0 3px rgba(0,120,212,0.4), 0 4px 16px rgba(0,0,0,0.15); }
  .node .accent { position: absolute; left: 0; top: 0; width: 6px; height: 100%; border-radius: 3px 0 0 3px; }
  .node .name { font-size: 13px; font-weight: 600; color: #1B1B1B; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
  .node .type { font-size: 11px; margin-top: 2px; }

  /* Edges — rendered as SVG overlay */
  .edges-layer { position: absolute; top: 0; left: 0; pointer-events: none; }
  .edge-path { fill: none; stroke-width: 1.5; }
  .edge-label {
    font-family: 'Segoe UI', system-ui, sans-serif; font-size: 10px;
    paint-order: stroke; stroke: white; stroke-width: 3px;
  }

  /* Groups */
  .group {
    position: absolute; border-radius: 12px; border: 1.5px dashed;
  }
  .group .group-label {
    position: absolute; top: -18px; left: 50%; transform: translateX(-50%);
    font-size: 12px; font-weight: 600; white-space: nowrap;
  }

  /* Tooltip */
  .tooltip {
    position: fixed; display: none; background: #1B1B1B; color: white;
    padding: 8px 12px; border-radius: 6px; font-size: 12px; max-width: 280px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.3); z-index: 1000; pointer-events: none;
  }
  .tooltip .tt-name { font-weight: 600; margin-bottom: 4px; }
  .tooltip .tt-type { opacity: 0.7; font-size: 11px; }
  .tooltip .tt-desc { margin-top: 4px; font-size: 11px; opacity: 0.85; }

  /* Legend */
  .legend {
    position: fixed; bottom: 12px; left: 12px; background: white;
    border-radius: 8px; padding: 10px 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    font-size: 11px; display: flex; gap: 12px; flex-wrap: wrap; max-width: 600px; z-index: 50;
  }
  .legend-item { display: flex; align-items: center; gap: 4px; }
  .legend-dot { width: 10px; height: 10px; border-radius: 50%; }
</style>
</head>
<body>

<div class="header">
  <h1>${esc(diagramTitle)}</h1>
  <div class="controls">
    <button onclick="zoomIn()">+</button>
    <button onclick="zoomOut()">−</button>
    <button onclick="resetView()">Reset</button>
    <button onclick="fitView()">Fit</button>
  </div>
  <div class="meta">Generated by Azure Architecture Diagram Builder</div>
</div>

<div class="canvas-container" id="container">
  <div class="canvas" id="canvas"></div>
</div>

<div class="tooltip" id="tooltip">
  <div class="tt-name"></div>
  <div class="tt-type"></div>
  <div class="tt-desc"></div>
</div>

<div class="legend" id="legend"></div>

<script>
// Layout data injected at generation time
const layout = ${layoutJson};

const CATEGORY_COLORS = {
  'ai + machine learning':  { bg: '#E8F0FE', border: '#4285F4' },
  'app services':           { bg: '#E8F4FD', border: '#0078D4' },
  'compute':                { bg: '#E8F4FD', border: '#0078D4' },
  'databases':              { bg: '#E6F4EA', border: '#0B8043' },
  'storage':                { bg: '#E6F4EA', border: '#137333' },
  'networking':             { bg: '#FFF3E0', border: '#E65100' },
  'analytics':              { bg: '#F3E8FD', border: '#7B1FA2' },
  'containers':             { bg: '#E0F7FA', border: '#00838F' },
  'integration':            { bg: '#FCE4EC', border: '#C62828' },
  'identity':               { bg: '#FFF8E1', border: '#F9A825' },
  'management + governance':{ bg: '#F1F8E9', border: '#558B2F' },
  'iot':                    { bg: '#E0F2F1', border: '#00695C' },
  'monitor':                { bg: '#EDE7F6', border: '#5E35B1' },
  'security':               { bg: '#FFEBEE', border: '#C62828' },
  'web':                    { bg: '#E3F2FD', border: '#1565C0' },
  'other':                  { bg: '#F5F5F5', border: '#616161' },
};

const CATEGORY_ICONS = {
  'ai + machine learning': '🤖', 'app services': '🌐', 'compute': '⚡',
  'databases': '🗄️', 'storage': '💾', 'networking': '🔗', 'analytics': '📊',
  'containers': '📦', 'integration': '🔄', 'identity': '🔑',
  'management + governance': '⚙️', 'iot': '📡', 'monitor': '📈',
  'security': '🛡️', 'web': '🌍', 'other': '☁️',
};

const EDGE_COLORS = { sync: '#0078D4', async: '#8764B8', optional: '#A0A0A0' };
const GROUP_COLORS = [
  { bg: '#F0F6FF08', border: '#0078D4' },
  { bg: '#F0FFF008', border: '#00B294' },
  { bg: '#FFF8F008', border: '#FFB900' },
  { bg: '#F8F0FF08', border: '#8764B8' },
  { bg: '#FFF0F008', border: '#D13438' },
  { bg: '#F0FFFF08', border: '#038387' },
];

// ── State ──
let scale = 1;
let offsetX = 0;
let offsetY = 0;
let isDragging = false;
let dragStartX = 0;
let dragStartY = 0;

const container = document.getElementById('container');
const canvas = document.getElementById('canvas');
const tooltip = document.getElementById('tooltip');

// ── Render ──
function render() {
  canvas.innerHTML = '';
  canvas.style.width = layout.width + 'px';
  canvas.style.height = layout.height + 'px';

  // Groups
  layout.groups.forEach((g, i) => {
    const gc = GROUP_COLORS[i % GROUP_COLORS.length];
    const el = document.createElement('div');
    el.className = 'group';
    el.style.left = (g.x - 12) + 'px';
    el.style.top = (g.y - 32) + 'px';
    el.style.width = (g.width + 24) + 'px';
    el.style.height = (g.height + 44) + 'px';
    el.style.borderColor = gc.border;
    el.style.background = gc.border + '08';
    el.innerHTML = '<div class="group-label" style="color:' + gc.border + '">' + esc(g.label) + '</div>';
    canvas.appendChild(el);
  });

  // Edges (SVG overlay)
  const svgNs = 'http://www.w3.org/2000/svg';
  const svg = document.createElementNS(svgNs, 'svg');
  svg.classList.add('edges-layer');
  svg.setAttribute('width', layout.width);
  svg.setAttribute('height', layout.height);
  svg.style.width = layout.width + 'px';
  svg.style.height = layout.height + 'px';

  // Arrowhead marker
  const defs = document.createElementNS(svgNs, 'defs');
  ['sync', 'async', 'optional'].forEach(t => {
    const marker = document.createElementNS(svgNs, 'marker');
    marker.setAttribute('id', 'arrow-' + t);
    marker.setAttribute('viewBox', '0 0 10 10');
    marker.setAttribute('refX', '10'); marker.setAttribute('refY', '5');
    marker.setAttribute('markerWidth', '8'); marker.setAttribute('markerHeight', '8');
    marker.setAttribute('orient', 'auto');
    const poly = document.createElementNS(svgNs, 'polygon');
    poly.setAttribute('points', '0,0 10,5 0,10');
    poly.setAttribute('fill', EDGE_COLORS[t]);
    marker.appendChild(poly);
    defs.appendChild(marker);
  });
  svg.appendChild(defs);

  layout.edges.forEach(e => {
    if (e.points.length < 2) return;
    const eType = e.type || 'sync';
    const color = EDGE_COLORS[eType] || EDGE_COLORS.sync;
    const d = e.points.map((p, i) => (i === 0 ? 'M' : 'L') + p.x + ' ' + p.y).join(' ');
    const path = document.createElementNS(svgNs, 'path');
    path.setAttribute('d', d);
    path.setAttribute('stroke', color);
    path.classList.add('edge-path');
    path.setAttribute('marker-end', 'url(#arrow-' + eType + ')');
    if (eType === 'async') path.setAttribute('stroke-dasharray', '6,4');
    if (eType === 'optional') path.setAttribute('stroke-dasharray', '4,4');
    svg.appendChild(path);

    if (e.label) {
      const mid = e.points[Math.floor(e.points.length / 2)];
      const text = document.createElementNS(svgNs, 'text');
      text.setAttribute('x', mid.x);
      text.setAttribute('y', mid.y - 4);
      text.setAttribute('text-anchor', 'middle');
      text.setAttribute('fill', color);
      text.classList.add('edge-label');
      text.textContent = e.label;
      svg.appendChild(text);
    }
  });
  canvas.appendChild(svg);

  // Nodes
  layout.nodes.forEach(n => {
    const cc = CATEGORY_COLORS[n.category] || CATEGORY_COLORS.other;
    const icon = CATEGORY_ICONS[n.category] || '☁️';
    const el = document.createElement('div');
    el.className = 'node';
    el.style.left = n.x + 'px';
    el.style.top = n.y + 'px';
    el.style.width = n.width + 'px';
    el.style.height = n.height + 'px';
    el.style.borderColor = cc.border;
    el.innerHTML =
      '<div class="accent" style="background:' + cc.border + '"></div>' +
      '<div class="name">' + icon + ' ' + esc(n.name) + '</div>' +
      '<div class="type" style="color:' + cc.border + '">' + esc(n.type) + '</div>';

    el.addEventListener('mouseenter', ev => showTooltip(ev, n));
    el.addEventListener('mouseleave', hideTooltip);
    el.addEventListener('click', () => {
      document.querySelectorAll('.node').forEach(nd => nd.classList.remove('highlighted'));
      el.classList.toggle('highlighted');
    });

    canvas.appendChild(el);
  });

  // Legend
  const cats = [...new Set(layout.nodes.map(n => n.category))].sort();
  const legendEl = document.getElementById('legend');
  legendEl.innerHTML = cats.map(c => {
    const cc = CATEGORY_COLORS[c] || CATEGORY_COLORS.other;
    return '<div class="legend-item"><div class="legend-dot" style="background:' + cc.border + '"></div>' + (CATEGORY_ICONS[c] || '') + ' ' + c + '</div>';
  }).join('');

  applyTransform();
}

function applyTransform() {
  canvas.style.transform = 'translate(' + offsetX + 'px,' + offsetY + 'px) scale(' + scale + ')';
}

// ── Tooltip ──
function showTooltip(ev, n) {
  const tt = tooltip;
  tt.style.display = 'block';
  tt.style.left = (ev.clientX + 12) + 'px';
  tt.style.top = (ev.clientY + 12) + 'px';
  tt.querySelector('.tt-name').textContent = n.name;
  tt.querySelector('.tt-type').textContent = n.type + ' (' + n.category + ')';
  tt.querySelector('.tt-desc').textContent = n.description || '';
}
function hideTooltip() { tooltip.style.display = 'none'; }

// ── Pan / Zoom ──
container.addEventListener('mousedown', e => {
  if (e.target.closest('.node')) return;
  isDragging = true; dragStartX = e.clientX - offsetX; dragStartY = e.clientY - offsetY;
  container.classList.add('dragging');
});
window.addEventListener('mousemove', e => {
  if (!isDragging) return;
  offsetX = e.clientX - dragStartX; offsetY = e.clientY - dragStartY;
  applyTransform();
});
window.addEventListener('mouseup', () => { isDragging = false; container.classList.remove('dragging'); });

container.addEventListener('wheel', e => {
  e.preventDefault();
  const delta = e.deltaY > 0 ? 0.9 : 1.1;
  const rect = container.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  const newScale = Math.max(0.1, Math.min(5, scale * delta));
  offsetX = mx - (mx - offsetX) * (newScale / scale);
  offsetY = my - (my - offsetY) * (newScale / scale);
  scale = newScale;
  applyTransform();
}, { passive: false });

function zoomIn() { scale = Math.min(5, scale * 1.2); applyTransform(); }
function zoomOut() { scale = Math.max(0.1, scale * 0.8); applyTransform(); }
function resetView() { scale = 1; offsetX = 0; offsetY = 0; applyTransform(); }
function fitView() {
  const cw = container.clientWidth;
  const ch = container.clientHeight;
  scale = Math.min(cw / layout.width, ch / layout.height) * 0.9;
  offsetX = (cw - layout.width * scale) / 2;
  offsetY = (ch - layout.height * scale) / 2;
  applyTransform();
}

function esc(s) { const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }

// ── Init ──
render();
fitView();
</script>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
