// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/**
 * Interactive HTML Renderer for SpecKit Diagrams
 *
 * Generates a self-contained HTML file with an interactive architecture
 * diagram. Features pan, zoom, hover tooltips, and click-to-highlight.
 * No external dependencies — works offline by opening the file in any browser.
 *
 * Designed to be included in az prototype SpecKit bundles alongside the
 * markdown documentation, replacing Mermaid with professional visuals.
 */

import type { LayoutResult } from './layoutEngine.js';

// ── Public API ─────────────────────────────────────────────────────────

export interface RenderHtmlOptions {
  /** Visual theme. Default: 'light'. */
  theme?: 'light' | 'dark';
  /** Author shown in the header metadata. */
  author?: string;
  /** Provenance label, e.g. the model that generated the design. */
  generatedBy?: string;
  /** Currency code for the total-cost readout. Default: 'USD'. */
  currency?: string;
}

/** Compact currency formatting for on-canvas cost badges. */
function fmtCost(n: number): string {
  if (n >= 10000) return `${Math.round(n / 1000)}k`;
  if (n >= 1000) return `${(n / 1000).toFixed(1).replace(/\.0$/, '')}k`;
  if (n >= 100) return `${Math.round(n)}`;
  return n.toFixed(2).replace(/\.?0+$/, '');
}

export function renderHtml(layout: LayoutResult, title?: string, options: RenderHtmlOptions = {}): string {
  const diagramTitle = title ?? 'Azure Architecture Diagram';
  const themeClass = options.theme === 'dark' ? 'dark' : 'light';

  // Serialize layout data for the client-side JS
  const layoutJson = JSON.stringify(layout);

  // Header metadata: author / date / provenance / total cost.
  const costedNodes = layout.nodes.filter(n => n.estimatedCost != null && n.estimatedCost > 0);
  const rangeNodes = layout.nodes.filter(
    n => (n.estimatedCost == null || n.estimatedCost <= 0) && n.costRange,
  );
  const totalCost = costedNodes.reduce((sum, n) => sum + (n.estimatedCost ?? 0), 0);
  const currency = options.currency ?? costedNodes[0]?.costCurrency ?? 'USD';
  const metaParts: string[] = [];
  if (options.author) metaParts.push(`Author: ${esc(options.author)}`);
  metaParts.push(new Date().toISOString().slice(0, 10));
  if (options.generatedBy) metaParts.push(`Generated by: ${esc(options.generatedBy)}`);
  if (costedNodes.length > 0) {
    const rangeNote = rangeNodes.length > 0 ? `; ${rangeNodes.length} usage-based as ranges` : '';
    metaParts.push(`Est. total ~$${fmtCost(totalCost)}/mo (${esc(currency)}, ${costedNodes.length}/${layout.nodes.length} priced${rangeNote})`);
  } else if (rangeNodes.length > 0) {
    metaParts.push(`Usage-based pricing — ${rangeNodes.length}/${layout.nodes.length} services as catalog ranges`);
  } else {
    metaParts.push('Azure Architecture Diagram Builder');
  }
  const headerMeta = metaParts.join(' · ');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${esc(diagramTitle)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Yu Gothic UI', 'Segoe UI', system-ui, -apple-system, sans-serif; background: #f8f9fa; overflow: hidden; }

  /* Dark theme */
  body.dark { background: #1E1E1E; }
  body.dark .node { background: #2D2D30; border-color: #3E3E42; box-shadow: 0 2px 8px rgba(0,0,0,0.4); }
  body.dark .node .name { color: #F3F3F3; }
  body.dark .node .cost { color: #4EC9A6; }
  body.dark .node .cost-range { color: #9A9A9A; }
  body.dark .legend { background: #252526; color: #C8C8C8; box-shadow: 0 2px 8px rgba(0,0,0,0.5); }
  body.dark .edge-label { stroke: #1E1E1E; }

  /* Header */
  .header {
    background: linear-gradient(135deg, #0078D4, #005A9E);
    color: white; padding: 12px 24px; display: flex; align-items: center; gap: 16px;
    box-shadow: 0 2px 8px rgba(0,0,0,0.15); z-index: 100; position: relative;
  }
  .header h1 { font-size: 18px; font-weight: 600; }
  .header .meta { font-size: 12px; opacity: 0.8; margin-left: auto; }
  .header .controls { display: flex; gap: 6px; }
  .header button {
    background: rgba(255,255,255,0.2); border: 1px solid rgba(255,255,255,0.3);
    color: white; padding: 4px 12px; border-radius: 4px; cursor: pointer; font-size: 12px;
  }
  .header button:hover { background: rgba(255,255,255,0.3); }

  /* Canvas */
  .canvas-container { width: 100vw; height: calc(100vh - 52px); overflow: hidden; position: relative; cursor: grab; }
  .canvas-container.dragging { cursor: grabbing; }
  .canvas { position: absolute; transform-origin: 0 0; }

  /* Nodes */
  .node {
    position: absolute; width: 200px; height: 70px; background: white;
    border-radius: 8px; border: 2px solid #ccc; box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    cursor: pointer; transition: box-shadow 0.2s, transform 0.2s;
    display: flex; flex-direction: column; justify-content: center; padding: 0 14px 0 20px;
    overflow: hidden;
  }
  .node:hover { box-shadow: 0 4px 16px rgba(0,0,0,0.15); transform: translateY(-1px); z-index: 10; }
  .node.highlighted { box-shadow: 0 0 0 3px rgba(0,120,212,0.4), 0 4px 16px rgba(0,0,0,0.15); }
  .node .accent { position: absolute; left: 0; top: 0; width: 6px; height: 100%; border-radius: 3px 0 0 3px; }
  .node .name { font-size: 13px; font-weight: 600; color: #1B1B1B; line-height: 1.15; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
  .node .type { font-size: 11px; margin-top: 2px; }
  .node .cost { position: absolute; right: 10px; bottom: 8px; font-size: 11px; font-weight: 600; color: #107C10; }
  .node .cost-range { font-size: 10px; font-weight: 500; font-style: italic; color: #8A8886; }

  /* Edges — rendered as SVG overlay */
  .edges-layer { position: absolute; top: 0; left: 0; pointer-events: none; }
  .edge-path { fill: none; stroke-width: 1.5; }
  .edge-label {
    font-family: 'Yu Gothic UI', 'Segoe UI', system-ui, sans-serif; font-size: 10px;
    paint-order: stroke; stroke: white; stroke-width: 3px;
  }

  /* Groups */
  .group {
    position: absolute; border-radius: 12px; border: 1.5px dashed;
  }
  .group .group-label {
    position: absolute; top: -18px; left: 50%; transform: translateX(-50%);
    font-size: 12px; font-weight: 600; white-space: nowrap;
  }

  /* Tooltip */
  .tooltip {
    position: fixed; display: none; background: #1B1B1B; color: white;
    padding: 8px 12px; border-radius: 6px; font-size: 12px; max-width: 280px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.3); z-index: 1000; pointer-events: none;
  }
  .tooltip .tt-name { font-weight: 600; margin-bottom: 4px; }
  .tooltip .tt-type { opacity: 0.7; font-size: 11px; }
  .tooltip .tt-desc { margin-top: 4px; font-size: 11px; opacity: 0.85; }

  /* Legend */
  .legend {
    position: fixed; bottom: 12px; left: 12px; background: white;
    border-radius: 8px; padding: 10px 14px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    font-size: 11px; display: flex; gap: 12px; flex-wrap: wrap; max-width: 600px; z-index: 50;
  }
  .legend-item { display: flex; align-items: center; gap: 4px; }
  .legend-dot { width: 10px; height: 10px; border-radius: 50%; }
</style>
</head>
<body class="${themeClass}">

<div class="header">
  <h1>${esc(diagramTitle)}</h1>
  <div class="controls">
    <button onclick="zoomIn()">+</button>
    <button onclick="zoomOut()">−</button>
    <button onclick="resetView()">Reset</button>
    <button onclick="fitView()">Fit</button>
  </div>
  <div class="meta">${headerMeta}</div>
</div>

<div class="canvas-container" id="container">
  <div class="canvas" id="canvas"></div>
</div>

<div class="tooltip" id="tooltip">
  <div class="tt-name"></div>
  <div class="tt-type"></div>
  <div class="tt-desc"></div>
</div>

<div class="legend" id="legend"></div>

<script>
// Layout data injected at generation time
const layout = ${layoutJson};

const CATEGORY_COLORS = {
  'ai + machine learning':  { bg: '#E8F0FE', border: '#4285F4' },
  'app services':           { bg: '#E8F4FD', border: '#0078D4' },
  'compute':                { bg: '#E8F4FD', border: '#0078D4' },
  'databases':              { bg: '#E6F4EA', border: '#0B8043' },
  'storage':                { bg: '#E6F4EA', border: '#137333' },
  'networking':             { bg: '#FFF3E0', border: '#E65100' },
  'analytics':              { bg: '#F3E8FD', border: '#7B1FA2' },
  'containers':             { bg: '#E0F7FA', border: '#00838F' },
  'integration':            { bg: '#FCE4EC', border: '#C62828' },
  'identity':               { bg: '#FFF8E1', border: '#F9A825' },
  'management + governance':{ bg: '#F1F8E9', border: '#558B2F' },
  'iot':                    { bg: '#E0F2F1', border: '#00695C' },
  'monitor':                { bg: '#EDE7F6', border: '#5E35B1' },
  'security':               { bg: '#FFEBEE', border: '#C62828' },
  'web':                    { bg: '#E3F2FD', border: '#1565C0' },
  'other':                  { bg: '#F5F5F5', border: '#616161' },
};

const CATEGORY_ICONS = {
  'ai + machine learning': '🤖', 'app services': '🌐', 'compute': '⚡',
  'databases': '🗄️', 'storage': '💾', 'networking': '🔗', 'analytics': '📊',
  'containers': '📦', 'integration': '🔄', 'identity': '🔑',
  'management + governance': '⚙️', 'iot': '📡', 'monitor': '📈',
  'security': '🛡️', 'web': '🌍', 'other': '☁️',
};

const EDGE_COLORS = { sync: '#0078D4', async: '#8764B8', optional: '#A0A0A0' };
const GROUP_COLORS = [
  { bg: '#F0F6FF08', border: '#0078D4' },
  { bg: '#F0FFF008', border: '#00B294' },
  { bg: '#FFF8F008', border: '#FFB900' },
  { bg: '#F8F0FF08', border: '#8764B8' },
  { bg: '#FFF0F008', border: '#D13438' },
  { bg: '#F0FFFF08', border: '#038387' },
];

// ── State ──
let scale = 1;
let offsetX = 0;
let offsetY = 0;
let isDragging = false;
let dragStartX = 0;
let dragStartY = 0;

const container = document.getElementById('container');
const canvas = document.getElementById('canvas');
const tooltip = document.getElementById('tooltip');

// ── Orthogonal edge routing (mirrors the SVG renderer) ──
function orthogonalRoute(points, direction) {
  const s = points[0], t = points[points.length - 1];
  let raw;
  if (direction === 'LR') {
    const midX = (s.x + t.x) / 2;
    raw = [s, { x: midX, y: s.y }, { x: midX, y: t.y }, t];
  } else {
    const midY = (s.y + t.y) / 2;
    raw = [s, { x: s.x, y: midY }, { x: t.x, y: midY }, t];
  }
  const out = [];
  for (const p of raw) {
    const last = out[out.length - 1];
    if (!last || Math.abs(last.x - p.x) > 0.5 || Math.abs(last.y - p.y) > 0.5) out.push(p);
  }
  return out.length >= 2 ? out : [s, t];
}
function roundedOrthoPathD(pts, radius) {
  radius = radius || 10;
  if (pts.length < 2) return '';
  if (pts.length === 2) return 'M ' + pts[0].x + ' ' + pts[0].y + ' L ' + pts[1].x + ' ' + pts[1].y;
  let d = 'M ' + pts[0].x + ' ' + pts[0].y;
  for (let i = 1; i < pts.length - 1; i++) {
    const prev = pts[i - 1], p = pts[i], next = pts[i + 1];
    const d1 = Math.hypot(p.x - prev.x, p.y - prev.y) || 1;
    const d2 = Math.hypot(next.x - p.x, next.y - p.y) || 1;
    const r = Math.min(radius, d1 / 2, d2 / 2);
    const c1x = p.x + ((prev.x - p.x) / d1) * r, c1y = p.y + ((prev.y - p.y) / d1) * r;
    const c2x = p.x + ((next.x - p.x) / d2) * r, c2y = p.y + ((next.y - p.y) / d2) * r;
    d += ' L ' + c1x + ' ' + c1y + ' Q ' + p.x + ' ' + p.y + ' ' + c2x + ' ' + c2y;
  }
  const last = pts[pts.length - 1];
  d += ' L ' + last.x + ' ' + last.y;
  return d;
}
function edgeLabelAnchor(route) {
  if (route.length >= 4) { const a = route[1], b = route[2]; return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 }; }
  const a = route[0], b = route[route.length - 1];
  return { x: (a.x + b.x) / 2, y: (a.y + b.y) / 2 };
}

// ── Render ──
function render() {
  canvas.innerHTML = '';
  canvas.style.width = layout.width + 'px';
  canvas.style.height = layout.height + 'px';

  // Groups
  layout.groups.forEach((g, i) => {
    const gc = GROUP_COLORS[i % GROUP_COLORS.length];
    const el = document.createElement('div');
    el.className = 'group';
    el.style.left = (g.x - 12) + 'px';
    el.style.top = (g.y - 32) + 'px';
    el.style.width = (g.width + 24) + 'px';
    el.style.height = (g.height + 44) + 'px';
    el.style.borderColor = gc.border;
    el.style.background = gc.border + '08';
    el.innerHTML = '<div class="group-label" style="color:' + gc.border + '">' + esc(g.label) + '</div>';
    canvas.appendChild(el);
  });

  // Edges (SVG overlay)
  const svgNs = 'http://www.w3.org/2000/svg';
  const svg = document.createElementNS(svgNs, 'svg');
  svg.classList.add('edges-layer');
  svg.setAttribute('width', layout.width);
  svg.setAttribute('height', layout.height);
  svg.style.width = layout.width + 'px';
  svg.style.height = layout.height + 'px';

  // Arrowhead marker
  const defs = document.createElementNS(svgNs, 'defs');
  ['sync', 'async', 'optional'].forEach(t => {
    const marker = document.createElementNS(svgNs, 'marker');
    marker.setAttribute('id', 'arrow-' + t);
    marker.setAttribute('viewBox', '0 0 10 10');
    marker.setAttribute('refX', '10'); marker.setAttribute('refY', '5');
    marker.setAttribute('markerWidth', '8'); marker.setAttribute('markerHeight', '8');
    marker.setAttribute('orient', 'auto');
    const poly = document.createElementNS(svgNs, 'polygon');
    poly.setAttribute('points', '0,0 10,5 0,10');
    poly.setAttribute('fill', EDGE_COLORS[t]);
    marker.appendChild(poly);
    defs.appendChild(marker);
  });
  svg.appendChild(defs);

  const edgeDir = layout.direction || 'TB';
  layout.edges.forEach(e => {
    if (e.points.length < 2) return;
    const eType = e.type || 'sync';
    const color = EDGE_COLORS[eType] || EDGE_COLORS.sync;
    const route = orthogonalRoute(e.points, edgeDir);
    const d = roundedOrthoPathD(route);
    const path = document.createElementNS(svgNs, 'path');
    path.setAttribute('d', d);
    path.setAttribute('stroke', color);
    path.classList.add('edge-path');
    path.setAttribute('marker-end', 'url(#arrow-' + eType + ')');
    if (eType === 'async') path.setAttribute('stroke-dasharray', '6,4');
    if (eType === 'optional') path.setAttribute('stroke-dasharray', '4,4');
    svg.appendChild(path);

    if (e.label) {
      const anchor = edgeLabelAnchor(route);
      const text = document.createElementNS(svgNs, 'text');
      text.setAttribute('x', anchor.x);
      text.setAttribute('y', anchor.y - 4);
      text.setAttribute('text-anchor', 'middle');
      text.setAttribute('fill', color);
      text.classList.add('edge-label');
      text.textContent = e.label;
      svg.appendChild(text);
    }
  });
  canvas.appendChild(svg);

  // Nodes
  layout.nodes.forEach(n => {
    const cc = CATEGORY_COLORS[n.category] || CATEGORY_COLORS.other;
    const icon = CATEGORY_ICONS[n.category] || '☁️';
    const el = document.createElement('div');
    el.className = 'node';
    el.style.left = n.x + 'px';
    el.style.top = n.y + 'px';
    el.style.width = n.width + 'px';
    el.style.height = n.height + 'px';
    el.style.borderColor = cc.border;
    el.innerHTML =
      '<div class="accent" style="background:' + cc.border + '"></div>' +
      '<div class="name">' + icon + ' ' + esc(n.name) + '</div>' +
      '<div class="type" style="color:' + cc.border + '">' + esc(n.type) + '</div>' +
      (n.estimatedCost ? '<div class="cost">~$' + fmtCost(n.estimatedCost) + '/mo</div>'
        : n.costRange ? '<div class="cost cost-range">' + esc(n.costRange) + '</div>' : '');

    el.addEventListener('mouseenter', ev => showTooltip(ev, n));
    el.addEventListener('mouseleave', hideTooltip);
    el.addEventListener('click', () => {
      document.querySelectorAll('.node').forEach(nd => nd.classList.remove('highlighted'));
      el.classList.toggle('highlighted');
    });

    canvas.appendChild(el);
  });

  // Legend
  const cats = [...new Set(layout.nodes.map(n => n.category))].sort();
  const legendEl = document.getElementById('legend');
  legendEl.innerHTML = cats.map(c => {
    const cc = CATEGORY_COLORS[c] || CATEGORY_COLORS.other;
    return '<div class="legend-item"><div class="legend-dot" style="background:' + cc.border + '"></div>' + (CATEGORY_ICONS[c] || '') + ' ' + c + '</div>';
  }).join('');

  applyTransform();
}

function applyTransform() {
  canvas.style.transform = 'translate(' + offsetX + 'px,' + offsetY + 'px) scale(' + scale + ')';
}

// ── Tooltip ──
function showTooltip(ev, n) {
  const tt = tooltip;
  tt.style.display = 'block';
  tt.style.left = (ev.clientX + 12) + 'px';
  tt.style.top = (ev.clientY + 12) + 'px';
  tt.querySelector('.tt-name').textContent = n.name;
  tt.querySelector('.tt-type').textContent = n.type + ' (' + n.category + ')';
  tt.querySelector('.tt-desc').textContent = n.description || '';
}
function hideTooltip() { tooltip.style.display = 'none'; }

// ── Pan / Zoom ──
container.addEventListener('mousedown', e => {
  if (e.target.closest('.node')) return;
  isDragging = true; dragStartX = e.clientX - offsetX; dragStartY = e.clientY - offsetY;
  container.classList.add('dragging');
});
window.addEventListener('mousemove', e => {
  if (!isDragging) return;
  offsetX = e.clientX - dragStartX; offsetY = e.clientY - dragStartY;
  applyTransform();
});
window.addEventListener('mouseup', () => { isDragging = false; container.classList.remove('dragging'); });

container.addEventListener('wheel', e => {
  e.preventDefault();
  const delta = e.deltaY > 0 ? 0.9 : 1.1;
  const rect = container.getBoundingClientRect();
  const mx = e.clientX - rect.left;
  const my = e.clientY - rect.top;
  const newScale = Math.max(0.1, Math.min(5, scale * delta));
  offsetX = mx - (mx - offsetX) * (newScale / scale);
  offsetY = my - (my - offsetY) * (newScale / scale);
  scale = newScale;
  applyTransform();
}, { passive: false });

function zoomIn() { scale = Math.min(5, scale * 1.2); applyTransform(); }
function zoomOut() { scale = Math.max(0.1, scale * 0.8); applyTransform(); }
function resetView() { scale = 1; offsetX = 0; offsetY = 0; applyTransform(); }
function fitView() {
  const cw = container.clientWidth;
  const ch = container.clientHeight;
  scale = Math.min(cw / layout.width, ch / layout.height) * 0.9;
  offsetX = (cw - layout.width * scale) / 2;
  offsetY = (ch - layout.height * scale) / 2;
  applyTransform();
}

function esc(s) { const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }

function fmtCost(n) {
  if (n >= 10000) return Math.round(n / 1000) + 'k';
  if (n >= 1000) return (n / 1000).toFixed(1).replace(/\\.0$/, '') + 'k';
  if (n >= 100) return String(Math.round(n));
  return n.toFixed(2).replace(/\\.?0+$/, '');
}

// ── Init ──
render();
fitView();
</script>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
